sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t arthurbonini/docker-react-travisci-aws -f Dockerfile.dev .

script:
    - docker run -e CI=true arthurbonini/docker-react-travisci-aws npm run test